version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB : service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0908
    ports:
      - "5433:5433"
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL : jdbc:postgresql://db:5432/service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0908
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
      SPRING_SECURITY_JWT_SECRET_KEY: AC2178015
    ports:
      - "8080-8080"
    depends_on:
      - db